server.port=8082
spring.application.name=pairing-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://103.90.226.48:5432/pairingdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:payment}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.flyway.enabled=false

